version: '3.8'
name: todo-api-deployed
services:
  db:
    image: mariadb:latest
    container_name: mariadb-container-deployed
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: todo
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .  # Path to the Dockerfile
    image: nestjs-todo-api
    container_name: nestjs-app
    env_file:
      - ".env.docker"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
    # command: sh -c "yarn start:prod && yarn typeorm migration:run"
    # command: ["./wait-for-db.sh", "db", "yarn typeorm migration:run && yarn start:prod"]

volumes:
  mariadb_data:

networks:
  backend:
